/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordle.guesser.app;

import static wordle.guesser.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        System.out.println(WordUtils.capitalize("result"));
    }
}
